//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1714cluken2h
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GearPassModelContainer : DbContext
    {
        public GearPassModelContainer()
            : base("name=GearPassModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Resort> Resorts { get; set; }
        public virtual DbSet<GearPass> GearPasses { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<SeasonPass> SeasonPasses { get; set; }
    }
}
