//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1714cluken2h
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeasonPass
    {
        public int Id { get; set; }
        public System.DateTime Year { get; set; }
        public decimal Cost { get; set; }
        public string SeasonPassDescription { get; set; }
    
        public virtual Resort Resort { get; set; }
        public virtual Sales Sale { get; set; }
    }
}
